version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8000:9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true

